# **Word Embedding Techniques using Embedding Layer in Keras**

In [1]:
import tensorflow as tf
print(tf.__version__)

2022-12-09 17:37:24.877570: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-09 17:37:25.038578: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe
2022-12-09 17:37:25.038602: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-09 17:37:25.904298: W tensorflow/compiler/xla/stream_executor/platform/default

2.11.0


In [2]:
sentences = ['Marvel series is my favourite movie',
              'the cup of coffee',
              'the cup of tea',
              'I am working as subject matter expert',
              'I am a good developer',
              'the cat is eating the food',
              'your lectures are good']

In [3]:
sentences

['Marvel series is my favourite movie',
 'the cup of coffee',
 'the cup of tea',
 'I am working as subject matter expert',
 'I am a good developer',
 'the cat is eating the food',
 'your lectures are good']

In [4]:
voc_size = 500

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

onehot_repr = [one_hot(words,voc_size) for words in sentences] 

In [6]:
onehot_repr

[[67, 355, 143, 141, 29, 291],
 [384, 208, 56, 408],
 [384, 208, 56, 418],
 [268, 37, 342, 139, 348, 98, 235],
 [268, 37, 473, 7, 44],
 [384, 12, 143, 19, 384, 144],
 [497, 120, 196, 7]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [9]:
print(embedded_docs)

[[  0   0  67 355 143 141  29 291]
 [  0   0   0   0 384 208  56 408]
 [  0   0   0   0 384 208  56 418]
 [  0 268  37 342 139 348  98 235]
 [  0   0   0 268  37 473   7  44]
 [  0   0 384  12 143  19 384 144]
 [  0   0   0   0 497 120 196   7]]


In [10]:
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam','mse')

2022-12-09 17:37:27.356569: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe
2022-12-09 17:37:27.356630: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-09 17:37:27.356666: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (hpeprereq-1.us-central1-a.c.deloitte-2022.internal): /proc/driver/nvidia/version does not exist
2022-12-09 17:37:27.357026: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performanc

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 96ms/step
[[[ 0.0466722   0.00823305  0.02065333 -0.03314508  0.01638866
    0.03044219 -0.01811396  0.02652207 -0.00379852  0.01625795]
  [ 0.0466722   0.00823305  0.02065333 -0.03314508  0.01638866
    0.03044219 -0.01811396  0.02652207 -0.00379852  0.01625795]
  [-0.01347943 -0.01941012 -0.00099878  0.04674285 -0.04466426
   -0.03067918  0.04598016 -0.01262902 -0.01197134  0.04788223]
  [ 0.03858839 -0.01758027  0.00371774 -0.03447851  0.02703622
   -0.00458044  0.03935471 -0.00957811 -0.00212612 -0.00752354]
  [ 0.01604256 -0.03107025  0.01575447 -0.04786141 -0.01812332
   -0.01901939 -0.04348482 -0.04283757  0.00165344  0.04700509]
  [ 0.00397017  0.04241543  0.03485955 -0.03842328  0.01302835
   -0.00483058 -0.00792034 -0.04794048  0.03393799  0.02600821]
  [ 0.02286165 -0.0255911   0.00616083  0.03417151  0.03621553
   -0.01471814  0.00256534  0.04045555 -0.0345006   0.02770771]
  [-0.01555651 -0.02091603 -0.042944    0.03772041 -0.03510

In [14]:
print(embedded_docs[0])

[  0   0  67 355 143 141  29 291]


In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 24ms/step
[[ 0.0466722   0.00823305  0.02065333 -0.03314508  0.01638866  0.03044219
  -0.01811396  0.02652207 -0.00379852  0.01625795]
 [ 0.0466722   0.00823305  0.02065333 -0.03314508  0.01638866  0.03044219
  -0.01811396  0.02652207 -0.00379852  0.01625795]
 [-0.01347943 -0.01941012 -0.00099878  0.04674285 -0.04466426 -0.03067918
   0.04598016 -0.01262902 -0.01197134  0.04788223]
 [ 0.03858839 -0.01758027  0.00371774 -0.03447851  0.02703622 -0.00458044
   0.03935471 -0.00957811 -0.00212612 -0.00752354]
 [ 0.01604256 -0.03107025  0.01575447 -0.04786141 -0.01812332 -0.01901939
  -0.04348482 -0.04283757  0.00165344  0.04700509]
 [ 0.00397017  0.04241543  0.03485955 -0.03842328  0.01302835 -0.00483058
  -0.00792034 -0.04794048  0.03393799  0.02600821]
 [ 0.02286165 -0.0255911   0.00616083  0.03417151  0.03621553 -0.01471814
   0.00256534  0.04045555 -0.0345006   0.02770771]
 [-0.01555651 -0.02091603 -0.042944    0.03772041 -0.03510829 -0.00782859