# **Word Embedding Techniques using Embedding Layer in Keras**

In [1]:
import tensorflow as tf
print(tf.__version__)

2022-11-28 16:17:14.757392: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.10.0


In [2]:
sentences = ['Marvel series is my favourite movie',
              'the cup of coffee',
              'the cup of tea',
              'I am working as subject matter expert',
              'I am a good developer',
              'the cat is eating the food',
              'your lectures are good']

In [3]:
sentences

['Marvel series is my favourite movie',
 'the cup of coffee',
 'the cup of tea',
 'I am working as subject matter expert',
 'I am a good developer',
 'the cat is eating the food',
 'your lectures are good']

In [4]:
voc_size = 500

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

onehot_repr = [one_hot(words,voc_size) for words in sentences] 

In [6]:
onehot_repr

[[283, 128, 443, 57, 476, 222],
 [363, 202, 166, 266],
 [363, 202, 166, 322],
 [112, 54, 478, 190, 44, 63, 455],
 [112, 54, 235, 82, 415],
 [363, 185, 443, 125, 363, 325],
 [314, 2, 367, 82]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [9]:
print(embedded_docs)

[[  0   0 283 128 443  57 476 222]
 [  0   0   0   0 363 202 166 266]
 [  0   0   0   0 363 202 166 322]
 [  0 112  54 478 190  44  63 455]
 [  0   0   0 112  54 235  82 415]
 [  0   0 363 185 443 125 363 325]
 [  0   0   0   0 314   2 367  82]]


In [10]:
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam','mse')

2022-11-28 16:17:35.092420: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-28 16:17:35.099464: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 152ms/step
[[[-0.0264665  -0.04108818 -0.04574072 -0.00420137  0.02797601
   -0.03476046 -0.02258263 -0.00629491 -0.01976715 -0.01513026]
  [-0.0264665  -0.04108818 -0.04574072 -0.00420137  0.02797601
   -0.03476046 -0.02258263 -0.00629491 -0.01976715 -0.01513026]
  [-0.03087514 -0.03974551  0.00388893  0.04510026 -0.04410353
    0.0269336   0.00546104  0.04003851 -0.03482064  0.03368587]
  [-0.02396339 -0.0275754   0.03013701  0.0143832  -0.02218617
    0.04219479 -0.01682223 -0.04722286  0.01668466 -0.00791387]
  [-0.03088337  0.00341371  0.009686    0.01594318 -0.01722163
   -0.00473521  0.01278206  0.03007822  0.03419318  0.00849223]
  [-0.02602981  0.02918825  0.04149671 -0.02905271 -0.03883452
   -0.00336198  0.00218866 -0.0298269   0.02165795  0.00882309]
  [-0.03473445  0.01248388  0.04607083  0.00461883 -0.02384665
    0.0300584  -0.0131515  -0.00602853  0.01561305 -0.02325197]
  [ 0.02820727  0.00147885 -0.03780096  0.04164684 -0.0402

In [14]:
print(embedded_docs[0])

[  0   0 283 128 443  57 476 222]


In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 29ms/step
[[-0.0264665  -0.04108818 -0.04574072 -0.00420137  0.02797601 -0.03476046
  -0.02258263 -0.00629491 -0.01976715 -0.01513026]
 [-0.0264665  -0.04108818 -0.04574072 -0.00420137  0.02797601 -0.03476046
  -0.02258263 -0.00629491 -0.01976715 -0.01513026]
 [-0.03087514 -0.03974551  0.00388893  0.04510026 -0.04410353  0.0269336
   0.00546104  0.04003851 -0.03482064  0.03368587]
 [-0.02396339 -0.0275754   0.03013701  0.0143832  -0.02218617  0.04219479
  -0.01682223 -0.04722286  0.01668466 -0.00791387]
 [-0.03088337  0.00341371  0.009686    0.01594318 -0.01722163 -0.00473521
   0.01278206  0.03007822  0.03419318  0.00849223]
 [-0.02602981  0.02918825  0.04149671 -0.02905271 -0.03883452 -0.00336198
   0.00218866 -0.0298269   0.02165795  0.00882309]
 [-0.03473445  0.01248388  0.04607083  0.00461883 -0.02384665  0.0300584
  -0.0131515  -0.00602853  0.01561305 -0.02325197]
 [ 0.02820727  0.00147885 -0.03780096  0.04164684 -0.04026992  0.02266318
 